### ISSUE TITLE
License mismatch between repository and release on crates.io

### ISSUE THREAD

**Issue by ousado** [Cosmian/crypto_core#48]
Cargo.toml and https://crates.io/crates/cosmian_crypto_core state it's released under MIT OR Apache-2.0 and LICENSE.md contains a dual AGPL/Commercial license. Both claim to be 9.0.0. 

Which is it?

**Comment by Manuthor** [comment]
thank you for your feedback. 
Indeed, the `license` specified in Cargo.toml was incorrect and has been removed in favor of `license-file` where the LICENSE.md is now specified

**Comment by ousado** [comment]
Maybe you should rethink that decision. As stated in your documentation, this is a thin layer around RustCrypto that even might disappear in the future, depending on how RustCrypto evolves. It doesn't look like your business depends in any way on this layer being licensed like the rest of your libraries. Releasing it under a permissive license would probably simply have the effect of greater adoption, which is free promotion for your company.
