### ISSUE TITLE
Use `secrecy`

### ISSUE THREAD

**Issue by tbrezot** [Cosmian/crypto_core#8]
Moving keys around can leave copies of the data in memory without the possibility of zeroizing them [[1]](https://docs.rs/zeroize/1.1.1/zeroize/#stackheap-zeroing-notes). It is advised to use the `secrecy` crate for a more secure management of the secrets [[2]](https://docs.rs/secrecy/latest/secrecy).

**Comment by bgrieder** [comment]
The use of the `zeroize` is now enforced on all secret.
